language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - "~/.cache/Cypress"
jobs:
  include:
    - stage: Code checking
      name: Lint
      script: yarn lint
    - name: Unit tests
      script: yarn test:unit
    - name: Build
      script: yarn build
